name: Run Tests with Playwright and xvfb

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:
    branches:
      - main # Run workflow on push to the 'main' branch

jobs:
  run-traffic-command:
    runs-on: ubuntu-latest

    env:
      proxy_password: ${{ secrets.proxy_server }}
      proxy_server: ${{ secrets.proxy_server }}

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Specify your required Node.js version

      # Step 3: Install system dependencies
      - name: Install xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # Step 4: Install project dependencies
      - name: Install project dependencies
        run: npm install

      # Step 5: Install Playwright tools
      - name: Install Playwright tools
        run: npx playwright install

      # Step 6: Install missing dependencies
      - name: Install missing dependencies
        run: npm install generative-bayesian-network

      # Step 7: Run the Traffic command with xvfb
      - name: Run traffic command with xvfb in parallel
        run: |
          xvfb-run --auto-servernum --server-num=1 --server-args='-screen 0 1920x1080x24' node traffic.js work=2 &
          wait
